[package]
name = "test-with-rust"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = { version = "1.0.80", features = ["parallel"] }
bindgen = "0.66.1"
toml = "0.7.6"
glob = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies]
mockall = { version = "0.14.0", features = ["nightly"] }
mockall_double = "0.3.0"

[package.metadata.foreigntest]
project_path = "../test-c-project-for-rust"
compile_commands_path = "compile_commands.json"
exclude_header_files_paths = ["lib/**", "source/**"]
extra_header_files_paths = [
    "source/app/**",
    "source/util/**",
]
support_header_files_path = "test-with-rust/support"
compile_args = [
    "-std=c99",
    "-fprofile-arcs",
    "-ftest-coverage",
    "-Wno-missing-field-initializers",
    "-funsigned-char",
    "-m32",
]
linker_args = ["--coverage", "-m32", "-lm"]
