use mockall::automock;

#[cfg_attr(test, automock)]
pub(crate) mod ffi {
    use super::*;
/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub fn lib_example_init() -> bool;
}
extern "C" {
    pub fn lib_example_show_text(p_text: *const lib_example_text_t) -> bool;
}
extern "C" {
    pub fn lib_example_show_int32(val: i32) -> bool;
}
extern "C" {
    pub fn lib_example_deinit();
}
}
pub use mock_ffi::*;
