#[cfg(test)]
use mockall::automock;
#[cfg_attr(test, automock)]
pub(crate) mod ffi {
use super::*;
/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub fn app_init();
}
extern "C" {
    pub fn app_run() -> ::std::os::raw::c_int;
}
}
/* automatically generated by rust-bindgen 0.66.1 */


